---

- name: Server Daten
  hosts: localhost
  become: true

  tasks:
   - name: User Erstellen
     ansible.builtin.user:
       name: jlemon
       comment: Jerry Lemon
       create_home: yes
       generate_ssh_key: yes
       ssh_key_bits: 2048
       ssh_key_file: .ssh/id_rsa


