---

   - name: Create Local user account and authorize SSH Key
     hosts: ubuntu_vms
     become: true


     tasks:
       - name: Create local user account
         user:
           name: ansible
           shell: /bin/bash
           password: '$6$J9JqEEQgtEFonZpQ$3MiVzGyEP5q0uQ3uSQAsi88VTEiHxVSWvqO4tNaIjfbVcVpQoFDvXkpu6OWY/QFZb/rUQujA0Gt.29ELXsulP1'
           groups: sudo
       - name: Add SSH Key to the user
         authorized_key:
           user: ansible
           key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPBi4kiyUb6ZmMpOzCjz+haOvWT8iTPW1jLVyeyA/DqP ilyal@MSI"
